### ISSUE TITLE
HW3 model 확인 질문

### ISSUE THREAD

**Issue by hwan517h1** [swsnu/swppfall2018#130]
README에 나온 것처럼 article의 author에 ForeingKey로 User를 넣었습니다.
makemigrations 시 기본 유저를 넣으라고 나오는데...
new_user = User.objects.create_user(username='swpp', password='iluvswpp')
와 상충되는 것 아닌가요?

혹은 Article의 column에 실습 예시처럼 title, content, author를 넣고
model를 확인하면 앞 부분은 통과되다가 new_article.save()에서 column이 없다고 에러가 뜹니다.
제가 어떤 과정을 빼먹은 것인가요?

**Comment by sanha** [comment]
Debugging을 요청하는 질문으로 보입니다. Django의 user model 사용법 등을 검색해 보시기 바랍니다.
