### ISSUE TITLE
[HW3] PUT, POST의 요청에서 수정되거나 새로 만들어진 결과를 Response의 Body로 돌려주어야하나요?

### ISSUE THREAD

**Issue by pbzweihander** [swsnu/swppfall2018#141]
HW2를 수행할 때 주어진 backend의 스펙에 따르면 PUT, POST 요청 시에 수정되거나 생성된 객체가 다시 Response의 Body로 돌아왔는데, HW3에는 그렇게 명시되어있지 않아 그냥 빈 200 Response를 주도록 구현했습니다. 돌려주거나 돌려주지 않아도 상관 없는 것인가요?

**Comment by sanha** [comment]
README에 어떻게 동작해야 하는지 명시되어있는 부분입니다. 그대로 구현해주세요.

**Comment by pbzweihander** [comment]
response body에 대해서는 명시되어있지 않은 것 같아서요.. status code만 맞으면 상관 없는 건가요?

**Comment by sanha** [comment]
JSON response가 아니라 HTTP Response를 적절한 status code와 함께 반환하셔야 합니다.
