### ISSUE TITLE
제출이 끝난 과제는 repository를 public으로 돌려도 되나요?

### ISSUE THREAD

**Issue by pbzweihander** [swsnu/swppfall2018#145]
과제 repo를 무조건 private으로 하라고 하셨는데, 제출이 끝난 과제는 public으로 공개해도 괜찮을까요?

**Comment by sanha** [comment]
Copy check script를 돌리므로 괜찮을 것 같은데, 교수님과 상의후 알려드리겠습니다.
다만 가능한 경우에도 HW 3 클레임 기간이 끝난 후 전환해주세요.

**Comment by sanha** [comment]
Public으로 돌려도 좋다고 하시네요.
